server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://111.231.20.113:3306/TradingDB
    username:
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-handlers-package: com.example.tradingsystem.mapper.typehandler
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: true
    db-config:
      id-type: assign_id
      update-strategy: not_null
  extension:
    enabled: true
    mapper-package: com.example.tradingsystem.mapper
    data-permission:
      enabled: true
